-- +goose Up
-- +goose StatementBegin

-- ─── oauth_clients ────────────────────────────────────────────────────────────
--
-- One row per registered OAuth client (e.g. ChatGPT registers once as a client
-- when the user first clicks "Add Connector" in ChatGPT).
--
-- This is a PUBLIC client — it has no client_secret.
-- Public clients can't securely store a secret (they're remote servers operated
-- by a third party), so the spec (RFC 7591) says: don't give them one.
-- Authentication happens via PKCE instead (see oauth_authorization_codes below).
--
-- redirect_uris: pinned at registration time; validated on every /authorize call.
-- Pinning prevents open-redirect attacks where an attacker swaps the redirect_uri
-- to steal the authorization code by redirecting it to their own server.

CREATE TABLE oauth_clients (
    id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    redirect_uris TEXT[]      NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── oauth_authorization_codes ────────────────────────────────────────────────
--
-- Short-lived (~60s), single-use codes issued after the user approves consent.
-- The code is sent to the client via a browser redirect; the client then exchanges
-- it for an access token at POST /token.
--
-- Why so short-lived? The code travels through the browser (URL bar, history,
-- referrer headers). 60 seconds limits the window an intercepted code is useful.
--
-- Why single-use? Once redeemed at /token, used_at is set. Any replay of the
-- same code is rejected. This is mandatory in OAuth 2.1 (§4.1.3).
--
-- code_challenge: SHA256(code_verifier) encoded as base64url.
--   - The client generates a random code_verifier, hashes it to get code_challenge,
--     and sends only the hash upfront (in /authorize). At /token, it sends the
--     original code_verifier. We re-hash it and compare — if they match, the
--     entity exchanging the code is the same one that started the flow.
--   - An attacker who intercepts the code can't redeem it without code_verifier.
--
-- redirect_uri is stored here too (not just on oauth_clients) because /token must
-- validate that the redirect_uri in the exchange matches the one used in /authorize.
-- RFC 6749 §4.1.3 requires this exact check as an additional forgery defence.

CREATE TABLE oauth_authorization_codes (
    id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The opaque value sent to the client in the redirect URL (?code=...).
    -- Generated by Postgres so it's guaranteed unique without application-level logic.
    code           UUID        NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    client_id      UUID        NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    user_id        UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- The exact redirect_uri the client used in /authorize; must match again at /token.
    redirect_uri   TEXT        NOT NULL,

    -- SHA256(code_verifier), base64url-encoded. Stored here so /token can verify
    -- SHA256(incoming code_verifier) == this value without knowing the verifier upfront.
    code_challenge TEXT        NOT NULL,

    -- 60 seconds from creation. Short enough that a stolen code is useless by the
    -- time an attacker could use it, long enough for a normal browser round-trip.
    expires_at     TIMESTAMPTZ NOT NULL,

    -- Set atomically when the code is consumed at /token. Any subsequent attempt to
    -- redeem the same code sees used_at IS NOT NULL and is rejected (ErrNotFound).
    used_at        TIMESTAMPTZ,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the lookup in ConsumeAuthorizationCode: WHERE code = $1
CREATE INDEX idx_auth_codes_code ON oauth_authorization_codes (code);

-- ─── oauth_refresh_tokens ─────────────────────────────────────────────────────
--
-- Long-lived tokens that let the client get new access tokens without re-prompting
-- the user. Unlike access tokens (short-lived JWTs that are self-contained), refresh
-- tokens are stored here so they can be revoked — e.g. when the user disconnects
-- ChatGPT from their Phrasely account.
--
-- Rotation: every time a refresh token is used, the old one is revoked (revoked_at
-- set) and a new one is issued. This limits the damage of a stolen refresh token:
-- if it's used by an attacker, the legitimate client's next attempt fails, alerting
-- us to a potential compromise (RFC 6749 §10.4).

CREATE TABLE oauth_refresh_tokens (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- The opaque token value sent to the client. Generated by Postgres.
    token      UUID        NOT NULL UNIQUE DEFAULT gen_random_uuid(),

    client_id  UUID        NOT NULL REFERENCES oauth_clients(id) ON DELETE CASCADE,
    user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Set when the token is consumed (rotated) or explicitly revoked.
    -- NULL means the token is still active.
    revoked_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for the lookup in ConsumeRefreshToken: WHERE token = $1
CREATE INDEX idx_refresh_tokens_token ON oauth_refresh_tokens (token);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS oauth_refresh_tokens;
DROP TABLE IF EXISTS oauth_authorization_codes;
DROP TABLE IF EXISTS oauth_clients;

-- +goose StatementEnd
