// Package oauth implements the internal OAuth 2.1 endpoints that back the public
// endpoints hosted by the mcp server. None of these routes are exposed directly
// to the internet — they are only reachable by mcp and frontend over the private
// internal network.
package oauth

import (
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"net/url"
	"regexp"
	"strings"
	"time"

	"github.com/andreistefanciprian/phrasely/internal/db"
	"github.com/andreistefanciprian/phrasely/internal/middleware"
	"github.com/gorilla/mux"
)

type Handler struct {
	store db.Store
}

func NewHandler(store db.Store) *Handler {
	return &Handler{store: store}
}

func (h *Handler) RegisterRoutes(r *mux.Router) {
	r.HandleFunc("/internal/oauth/register", h.register).Methods(http.MethodPost)
	r.HandleFunc("/internal/oauth/authorize", h.authorize).Methods(http.MethodPost)
}

// registerRequest is the body of POST /internal/oauth/register.
// It mirrors the RFC 7591 Dynamic Client Registration request, simplified to
// the fields we actually use.
type registerRequest struct {
	// RedirectURIs is the list of URIs the client is allowed to redirect to after
	// the user approves consent. We pin these at registration time and validate
	// them on every /authorize call — this is the key open-redirect defence.
	// An attacker who tries to swap in their own redirect_uri at /authorize will
	// be rejected because it won't match what was registered here.
	RedirectURIs []string `json:"redirect_uris"`
}

// registerResponse is the body returned on success.
// Per RFC 7591 §3.2.1 the server echoes back the registered metadata plus
// the assigned client_id.
type registerResponse struct {
	// ClientID is the opaque identifier assigned to this client. The client
	// includes it in every subsequent /authorize and /token request so the
	// server knows which registration to validate against.
	ClientID     string   `json:"client_id"`
	RedirectURIs []string `json:"redirect_uris"`
}

// register handles POST /internal/oauth/register.
// Called by mcp (which proxies the public /register endpoint).
// It validates the redirect URIs, stores the client, and returns a client_id.
func (h *Handler) register(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 4*1024) // 4 KB — generous for a list of URIs

	var req registerRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondErr(w, http.StatusBadRequest, "invalid request body")
		return
	}

	// At least one redirect_uri is required. RFC 7591 doesn't mandate this
	// for all client types, but ChatGPT's connector flow always provides one,
	// and we need it to validate the /authorize redirect later.
	if len(req.RedirectURIs) == 0 {
		respondErr(w, http.StatusBadRequest, "at least one redirect_uri is required")
		return
	}

	// Validate every URI before persisting anything.
	// We accept http:// to allow local dev (e.g. http://localhost:...).
	// In production, ChatGPT always uses https://.
	for _, raw := range req.RedirectURIs {
		if err := validateRedirectURI(raw); err != nil {
			respondErr(w, http.StatusBadRequest, "invalid redirect_uri: "+err.Error())
			return
		}
	}

	client, err := h.store.CreateOAuthClient(r.Context(), req.RedirectURIs)
	if err != nil {
		slog.Error("create oauth client", "error", err)
		respondErr(w, http.StatusInternalServerError, "failed to register client")
		return
	}

	respond(w, http.StatusCreated, registerResponse{
		ClientID:     client.ID,
		RedirectURIs: client.RedirectURIs,
	})
}

// authorizeRequest is the body of POST /internal/oauth/authorize.
// Called by the frontend after the user approves consent on the /authorize screen.
type authorizeRequest struct {
	// ClientID identifies the registered OAuth client (from /register).
	ClientID string `json:"client_id"`

	// RedirectURI is the URI the code will be appended to. Must exactly match
	// one of the URIs registered at /register — this prevents open redirect attacks.
	RedirectURI string `json:"redirect_uri"`

	// CodeChallenge is BASE64URL(SHA256(code_verifier)). Generated by the client
	// (ChatGPT) and stored here so we can verify the code_verifier at /token time.
	// The raw code_verifier never leaves the client — storing only the hash means
	// a DB leak can't be used to forge tokens.
	CodeChallenge string `json:"code_challenge"`
}

// authorizeResponse is returned on success.
type authorizeResponse struct {
	// Code is the short-lived (~60s) single-use authorization code.
	// The frontend appends it to the redirect_uri and sends the browser back to ChatGPT.
	Code string `json:"code"`
}

// authCodeTTL is how long an authorization code is valid for exchange at /token.
// RFC 6749 §4.1.2 recommends a maximum of 10 minutes; 60 seconds is tighter and
// common in production — the client exchanges the code immediately after redirect.
const authCodeTTL = 60 * time.Second

// base64urlRE matches the base64url alphabet (no padding). A SHA256 hash encoded
// this way is always exactly 43 characters.
var base64urlRE = regexp.MustCompile(`^[A-Za-z0-9_-]{43}$`)

// authorize handles POST /internal/oauth/authorize.
// Called by the frontend (over the private network) after the user approves consent.
// It validates the client + redirect URI, stores a PKCE authorization code, and
// returns it so the frontend can redirect the browser back to the OAuth client.
func (h *Handler) authorize(w http.ResponseWriter, r *http.Request) {
	r.Body = http.MaxBytesReader(w, r.Body, 4*1024)

	// user_id is injected by the JWT middleware — the user must be logged in to
	// the frontend before they can reach the consent screen.
	userID := middleware.UserIDFromContext(r.Context())
	if userID == "" {
		respondErr(w, http.StatusUnauthorized, "authentication required")
		return
	}

	var req authorizeRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondErr(w, http.StatusBadRequest, "invalid request body")
		return
	}

	if req.ClientID == "" || req.RedirectURI == "" || req.CodeChallenge == "" {
		respondErr(w, http.StatusBadRequest, "client_id, redirect_uri, and code_challenge are required")
		return
	}

	// code_challenge must be BASE64URL(SHA256(verifier)) — always 43 chars, no padding.
	// Rejecting obviously wrong values early avoids storing garbage in the DB.
	if !base64urlRE.MatchString(req.CodeChallenge) {
		respondErr(w, http.StatusBadRequest, "code_challenge must be base64url-encoded SHA256 (43 chars, no padding)")
		return
	}

	// Look up the registered client to validate client_id and retrieve redirect_uris.
	client, err := h.store.GetOAuthClient(r.Context(), req.ClientID)
	if err != nil {
		if errors.Is(err, db.ErrNotFound) {
			respondErr(w, http.StatusBadRequest, "unknown client_id")
			return
		}
		slog.Error("get oauth client", "error", err)
		respondErr(w, http.StatusInternalServerError, "internal error")
		return
	}

	// redirect_uri must exactly match one of the registered URIs.
	// This is the open-redirect defence: an attacker cannot swap in their own URI
	// at /authorize because it won't match what was pinned at /register.
	if !redirectURIAllowed(req.RedirectURI, client.RedirectURIs) {
		respondErr(w, http.StatusBadRequest, "redirect_uri not registered for this client")
		return
	}

	code, err := h.store.CreateAuthorizationCode(r.Context(), db.CreateAuthCodeRequest{
		ClientID:      req.ClientID,
		UserID:        userID,
		RedirectURI:   req.RedirectURI,
		CodeChallenge: req.CodeChallenge,
		ExpiresAt:     time.Now().Add(authCodeTTL),
	})
	if err != nil {
		slog.Error("create authorization code", "error", err)
		respondErr(w, http.StatusInternalServerError, "failed to issue authorization code")
		return
	}

	respond(w, http.StatusOK, authorizeResponse{Code: code.Code})
}

// redirectURIAllowed reports whether uri exactly matches one of the allowed URIs.
// Exact match only — no prefix or suffix matching — to prevent redirect hijacking.
func redirectURIAllowed(uri string, allowed []string) bool {
	for _, a := range allowed {
		if uri == a {
			return true
		}
	}
	return false
}

// validateRedirectURI checks that a redirect_uri is a well-formed http/https URL.
// We deliberately do not allow:
//   - fragment components (#...) — RFC 6749 §3.1.2 forbids them. Note: we check
//     the raw string for '#' because url.ParseRequestURI silently strips fragments,
//     so u.Fragment would always appear empty even when a fragment is present.
//   - non-http(s) schemes — limits attack surface (no javascript:, data:, etc.)
func validateRedirectURI(raw string) error {
	if strings.Contains(raw, "#") {
		return errors.New("fragments not allowed in redirect_uri (RFC 6749 §3.1.2)")
	}
	u, err := url.ParseRequestURI(raw)
	if err != nil {
		return err
	}
	if u.Scheme != "http" && u.Scheme != "https" {
		return errors.New("scheme must be http or https")
	}
	return nil
}

func respond(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(body)
}

func respondErr(w http.ResponseWriter, status int, msg string) {
	respond(w, status, map[string]string{"error": msg})
}
